### ISSUE TITLE
Return to original mailbox handler instead of shellcode discarding opcode?

### ISSUE THREAD

**Issue by Cryptiiiic** [NyanSatan/Anya#5]
Return to original mailbox handler instead of shellcode discarding opcode?
This would allow running ap decrypt and sep decrypt at the same time. This isn't possible on roms with dpa seeding. It will time timeout because sep never executes the code needed when called from aes_hw_crypto_cmd. The shellcode probably destroys the mailbox handler registers so they may need to be saved and restored in order to implement this. However, the easiest solution would be just to implement dpa opcode in the shellcode loop.

**Comment by NyanSatan** [comment]
Hello!

I'm working on a new majorly improved version of Anya. It's basically ready - I'm just waiting for someone to test it on certain platforms that I don't have

There I got rid of the SEP shellcode altogether and do RW via CoreSight - that allows, for example, to support devices with SEP Boot Monitor (A13 and later)

Can you give an example of a platform with that DPA seeding thing? Is it A11? Because I don't remember having such an issue on A12+, but maybe I just didn't test such case

Also if you need the new Anya code for something, let me know, I can share it privately!

**Comment by Cryptiiiic** [comment]
From SecureROM’s I’ve looked at a11 and a12 both use dpa. Another issue is that memcpy usually writes byte by byte. That’s fine an all but aes base at least on some seproms only allows 4 byte aligned writes. So it’s better to add the memcpy that writes by 4’s alongside the shellcode.

**Comment by NyanSatan** [comment]
Speaking of the `memcpy()` - yea, I also noticed it after some time, epic fail of mine! But seems to work on A12/S4/S5. And soon the whole thing is gonna be discarded anyway

Speaking of the DPA thing - just tried to decrypt AP KBAGs after decrypting some SEP ones with the new Anya (which halts the SEP core forever in order to do the CoreSight magic) and it seems to work for some reason:

```
noone@noones-MacBook-Air Anya % build/anyactl -k 371AB6EE90FFED3F33AD0284DCDB140D8141A4CF8DC638A0371BC217145F8D0B59F38CB11F2FA6200B7A746B423CFD5B
found: CPID:8020 CPFM:00 ECID:REDACTED
3DE38EB303B61B439E20F0662F1878869FAF45FD4D2DF8EA105A7742EFE32B76EF2A0D973C834446C6E312703A475E28

noone@noones-MacBook-Air Anya % build/anyactl -s -k 67293F69FE8B7A144992836931D5C9393382342FF3376F3B4F7AD805107B30523C126A27997A63D874C4F5D5F3268A2D
found: CPID:8020 CPFM:00 ECID:REDACTED
will use SEP GID
153EE783BDAF82F93E0905774ABB116CB90972D61BA9ADFE15AFAC69A826B436DCA36B53BE7B550D4098E592A0E49FCB

noone@noones-MacBook-Air Anya % build/anyactl -k 371AB6EE90FFED3F33AD0284DCDB140D8141A4CF8DC638A0371BC217145F8D0B59F38CB11F2FA6200B7A746B423CFD5B   
found: CPID:8020 CPFM:00 ECID:REDACTED
3DE38EB303B61B439E20F0662F1878869FAF45FD4D2DF8EA105A7742EFE32B76EF2A0D973C834446C6E312703A475E28

noone@noones-MacBook-Air Anya % build/anyactl -s -k 67293F69FE8B7A144992836931D5C9393382342FF3376F3B4F7AD805107B30523C126A27997A63D874C4F5D5F3268A2D
found: CPID:8020 CPFM:00 ECID:REDACTED
will use SEP GID
153EE783BDAF82F93E0905774ABB116CB90972D61BA9ADFE15AFAC69A826B436DCA36B53BE7B550D4098E592A0E49FCB

noone@noones-MacBook-Air Anya % build/anyactl -s -b 10000                                                                                           
found: CPID:8020 CPFM:00 ECID:REDACTED
will use SEP GID
decrypting...
decrypted 10000 KBAGs in 5.732538 seconds, average - 1744.427979 KBAGs/sec

noone@noones-MacBook-Air Anya % build/anyactl -b 10000  
found: CPID:8020 CPFM:00 ECID:REDACTED
decrypting...
decrypted 10000 KBAGs in 0.497060 seconds, average - 20118.294922 KBAGs/sec
```

Perhaps, the DPA thing is not used on GID0 decryption path?

**Comment by NyanSatan** [comment]
Should be non-issue in the newest version
